#!/bin/bash

aptaddrepo+=()
dnfaddrepo+=()
aptinstall+=()
dnfinstall+=()
config+=()
gsetting+=()
dconf+=()
run+=()
sudorun+=()


usage() {
    echo "usage: install <config>"
}

process_item() {
    if [ ! -f "items/$1.sh" ]; then
        echo "Error: Failed to process hook for \"$1\""
        exit 3
    fi
    source "items/$1.sh"
}


main() {
    if [ ! $# -eq 1 ]; then
        usage
        exit 1
    fi

    if [ ! -f "$1" ]; then
        echo "Error: Invalid file \"$1\""
        exit 2
    fi

    for item in $(cat "$1"); do
        echo "Processing hooks for \"$item\""
        process_item "$item"
    done

    echo "aptaddrepo = ${aptaddrepo[@]}"
    echo "dnfaddrepo = ${dnfaddrepo[@]}"
    echo "aptinstall = ${aptinstall[@]}"
    echo "dnfinstall = ${dnfinstall[@]}"
    echo "config = ${config[@]}"
    echo "gsetting = ${gsetting[@]}"
    echo "dconf = ${dconf[@]}"
    echo "run = ${run[@]}"
    echo "sudorun = ${sudorun[@]}"
}

main $@
