#!/bin/bash

source common


get_distro() {
    file="packages/distros"
    local list=()
    while read line; do
        id=$(echo $line | cut -d "," -f 1)
        name=$(echo $line | cut -d "," -f 2)
        list+=("$id" "$name" "OFF")
    done < "$file"
    local num=$(cat "$file" | wc -l)
    list[2]="ON"

    dialog \
        --title "jsetup" \
        --notags \
        --radiolist "Please select a distro" $(expr $num + 7) 40 \
        $num "${list[@]}" \
        3>&1 1>&2 2>&3
}


get_packages() {
    local list=()
    while read line; do
        id=$(echo $line | cut -d "," -f 1)
        name=$(echo $line | cut -d "," -f 2)
        list+=("$id" "$name" "OFF")
    done < "packages/$1/packages"
    local num=$(cat "packages/$1/packages" | wc -l)

    dialog \
        --title "jsetup" \
        --notags \
        --checklist "Please select packages" $(expr $num + 7) 30 \
        $num "${list[@]}" \
        3>&1 1>&2 2>&3
}


main() {
    sudo -v

    # Get Distro
    distro=$(get_distro)
    if [ $? -ne 0 ]; then
        echo
        return 0
    fi

    # Get packages
    packages=$(get_packages $distro)
    if [ $? -ne 0 ]; then
        echo
        return 0
    fi

    # Install packages
    echo
    for package in $packages; do
        echo
        info "Installing package \"$package\""
        info "==============================================================================="
        bash "packages/$distro/$package"
        if [ $? -ne 0 ]; then
            error "Error: package $package failed!"
        fi
    done
}

main $@
