#!/bin/bash

# Helper Functions
# -----------------------------------------------------------------------------

to_abs_dir() {
    if [[ "$1" == /* ]]; then
        echo "$1"
    else
        echo "$(pwd)/$1"
    fi
}

to_rel_dir() {
    python -c "import os.path; print os.path.relpath(\"${1}\", \"${2}\")"
}



# Argument Processing
# -----------------------------------------------------------------------------

workingdir=.
exportdir=$(pwd)
name="None"

# Check that we have dockerdir
arg_check_config() {
    if [ -z "$DOCKERDIR" ]; then
        echo "Error: DOCKERDIR is undefined"
        exit 1
    fi
}

# Check that the specified docker image has been defined
arg_image() {
    name="$1"
    if [ ! -f "$DOCKERDIR/$name/Dockerfile" ]; then
        echo "Error: $name has no Dockerfile"
        exit 1
    fi
}


# Docker commands
# -----------------------------------------------------------------------------
docker_build() {
    # Attempt to build the image
    # TODO don't do this if the image is ready
    docker build -t "$name" "$DOCKERDIR/$name"
}

docker_run() {
    # Run our command in the docker image
    docker run -it -w /${dirname}/${workingdir} -u "$UID:$UID" -v "${exportdir}:/${dirname}" "$name" $@
}


# Main
# -----------------------------------------------------------------------------
main() {
    arg_check_config
    if [ "$1" == "-d" ]; then
        exportdir=$(to_abs_dir "$2")
        to_abs_dir "$2"
        workingdir=$(to_rel_dir $(pwd) $exportdir)
        shift 2
    fi
    arg_image $@
    shift 1
    dirname=$(basename $(readlink -f $exportdir))


    output=$(docker_build)
    if [[ "$output" == *"Running in"* ]]; then
        echo "$output"
        echo "
===============================================================================
"
    fi
    docker_run $@
}

main $@
